[General]
# NeetOs SDDM Configuration

[Theme]
Current=breeze
CursorTheme=breeze_cursors

[X11]
ServerArguments=-nolisten tcp

[Wayland]
EnableHiDPI=true
SessionDir=/usr/share/wayland-sessions

[Users]
MaximumUid=60000
MinimumUid=1000
HideUsers=
HideShells=/bin/false,/usr/bin/nologin
RememberLastUser=true
RememberLastSession=true

[Autologin]
# Uncomment for auto-login
# User=neet
# Session=hyprland
